variables:
  APP_NAME: touch-web-cleint
  APP_PORT: 80
  DEPLOY_BASE_HREF: /touch/
  DEPLOY_PUBLIC_PORT: 8000
  DEPLOY_NETWORK_NAME: proxy
  DOCKER_IMAGE_NAME: $DOCKER_ORGANIZATION/$APP_NAME
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - publish
  - deploy

# BUILD

build:
  stage: build
  image: node:16-alpine
  before_script:
    - yarn install --frozen-lockfile
    - yarn ngcc
  script:
    - yarn build --base-href $DEPLOY_BASE_HREF
  artifacts:
    paths:
      - dist
    expire_in: 1 day

# PUBLISH

publish:
  stage: publish
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
  after_script:
    - docker login --username=$DOCKER_USER --password=$DOCKER_TOKEN
    - docker push $DOCKER_IMAGE_NAME
  needs:
    - build

# DEPLOY

deploy:
  stage: deploy
  image: ictu/sshpass
  needs:
    - publish
  before_script:
    - alias ssh-pass-server='sshpass -p "$SDAL_DEFAULT_PASSWORD" ssh -oStrictHostKeyChecking=no $SDAL_DEFAULT_USERNAME@$SDAL_DEFAULT_IP'
  script:
    - ssh-pass-server docker pull $DOCKER_IMAGE_NAME
    - ssh-pass-server docker rm -f $APP_NAME || true
    - ssh-pass-server docker run -d -p $DEPLOY_PUBLIC_PORT:$APP_PORT --network=$DEPLOY_NETWORK_NAME --name $APP_NAME $DOCKER_IMAGE_NAME
